# Generated by Django 4.1.3 on 2022-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystore", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name_plural": "Inventory"},
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
