# Generated by Django 4.1.3 on 2022-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystore", "0002_alter_inventory_options_alter_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
